### ISSUE TITLE
from model import S3Net --> ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by mhaut** [ZhaohuiXue/S3Net#2]
Dear author,

I am trying to run your code, however, the file model.py does not exist. Would you be so kind as to publish it?

Thank you.

**Comment by ZhaohuiXue** [comment]
I will send you by email.

**Comment by liuzuo-byte** [comment]
作者你好，能发我一份model.py文件吗，我将引用这篇论文，并把它作为我的对比实验，我将万分感激，祝你工作顺利，身体健康
